[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
learnings = "GNKwvk7KSWMxUS8w4s6S3qSL6gpU4jTVwYhnuzSQpizz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "../mykey.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
